
tag: ''

# seed: 42
seed: 37
# case_name: magicSqure
# case_name: scan65
case_name: DJI951
root_dir: /data3/zzy/data_lab/${case_name}
# root_dir: /data3/zzy/public_data/${case_name}
log_dir: ${root_dir}/logs
grid_X: 1
grid_Y: 1
mask_dir: ${root_dir}/mask/${grid_X}x${grid_Y}
save_dir: ${root_dir}/exp/${grid_X}x${grid_Y}
ckpt_dir: ${save_dir}
model_start_num: 0 # 开始从第几个模型训练
validate_freq: 300
is_continue: false
use_DDP: false
dataset:
  downsample: 0.4
  use_random: true
  name: colmap
  root_dir: ${root_dir}
  ray_sampling_strategy: same_image
  # batch_size: 128
  # batch_size: 2048
  # batch_size: 3248
  # batch_size: 4096
  batch_size: 8192
  split_num: 1500
  model_start_num: ${model_start_num}
  mask_dir: ${mask_dir}
  grid_X: ${grid_X}
  grid_Y: ${grid_Y}
  batch_num: 400000
  
model:
  name: nerf
  aabb:
    use_custom_radius: false
  grid_update_freq: 16
  grid_resolution: 128 # 128
  num_samples_per_ray: 512 # 512
  grid_prune: true
  use_nerfacc: true
  dynamic_ray_sampling: true
  batch_image_sampling: true
  randomized: true
  ray_chunk: 4096
  geometry_network:
    radius: ${model.aabb.radius}
    radius_z: ${model.aabb.radius_z}
    feature_dim: 13
    sdf_activation: none
    sdf_bias: 0.
    grad_type: analytic
    isosurface:
      method: mc
      resolution: 512
      chunk: 2097152
      threshold: 0.
    xyz_encoding_config:
      otype: Grid
      type: Hash
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 20 # 大小只影响hash冲突
      base_resolution: 16
      
      # per_level_scale: 1.381912879967776 #N_max = 2048
      per_level_scale: 1.447269237440378 #N_max = 4096
      # per_level_scale: 1.515716566510398 #N_max = 8192
      # per_level_scale: 1.5874010519681996 #N_max = 16384
      # per_level_scale: 1.6624757922855755 #N_max = 32768
      # per_level_scale: 1.7411011265922482 #N_max = 65536

      # include_xyz: true
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: none
      n_neurons: 128
      n_hidden_layers: 2
      # sphere_init: true
      # weight_norm: true
  color_net:
    name: volume-radiance
    use_normal: false
    dir_encoding_config:
      # otype: SphericalHarmonics
      # degree: 4    
      otype: Frequency
      degree: 8
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: none
      n_neurons: 64
      n_hidden_layers: 2
    color_activation: sigmoid
  
system:
  name: nerf-system
  loss:
    lambda_rgb: 1.
    lambda_opacity: 0.1
    lambda_mask: 0.
  optimizer:
    # name: Adam
    name: FusedAdam
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry_network:
          lr: 3.e-3
      color_net:
          lr: 3.e-3
  scheduler:
    name: ExponentialLR
    interval: step
    args:
      step_size: 80
      # gamma: 0.99
      # gamma: 1.01
      gamma: 0.98

checkpoint:
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}

trainer:
  max_steps: 2000000
  log_every_n_steps: 100
  num_sanity_val_steps: 0
  # val_check_interval: 500
  limit_train_batches: 1.0
  limit_val_batches: 1
  enable_progress_bar: true 
  precision: 16
